mysql:
  user: root
  pwd: admin123
  host: 192.168.7.114
  port: 3306
  dbName: fetion
  charset: utf8

# 数据库连接
DB:
  dns: root:admin123@tcp(localhost:3306)/fetion?charset=utf8&parseTime=True&loc=Local
  MaxIdleConns: 50
  MaxOpenConns: 200

# redis
redis:
  addr: localhost:6379
  pwd: "" # no pwd set
  db: 0 # use default DB
  poolSize: 30
  minIdleConn: 30